context:
  version: 0.3.0

package:
  name: rargs
  version: ${{ version }}

source:
  url: https://github.com/lotabout/rargs/archive/v${{ version }}.tar.gz
  sha256: 22d9aa4368a0f9d1fd82391439d3aabf4ddfb24ad674a680d6407c9e22969da3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rargs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Util like xargs + awk with pattern matching support
  homepage: https://github.com/lotabout/rargs
  repository: https://github.com/lotabout/rargs

extra:
  recipe-maintainers:
    - danielnachun
